ca-certificates           2025.2.25            
certifi                   2025.4.26                
charset-normalizer        3.4.2                    
colorama                  0.4.6                    
contourpy                 1.1.1                   
cycler                    0.12.1                  
filelock                  3.13.1                  
fonttools                 4.57.0                   
fsspec                    2024.6.1                 
idna                      3.10                     
importlib-resources       6.4.5                    
jinja2                    3.1.4                   
kiwisolver                1.4.7                   
libffi                    3.4.4               
markupsafe                2.1.5                    
matplotlib                3.7.5                   
mpmath                    1.3.0                   
networkx                  3.0                      
numpy                     1.24.1                   
opencv-python             4.11.0.86               
openssl                   3.0.16               
openvino                  2024.4.0                 
openvino-telemetry        2025.1.0                
packaging                 25.0                     
pandas                    2.0.3                    
pillow                    10.2.0                   
pip                       24.2             
psutil                    7.0.0                    
py-cpuinfo                9.0.0                    
pyparsing                 3.1.4                    
python                    3.8.20               
python-dateutil           2.9.0.post0             
pytz                      2025.2                   
pyyaml                    6.0.2                   
requests                  2.32.3                   
scipy                     1.10.1                   
setuptools                75.1.0          
six                       1.17.0                  
sqlite                    3.45.3              
sympy                     1.13.3                  
torch                     2.4.1+cu118             
torchaudio                2.4.1+cu118             
torchvision               0.19.1+cu118             
tqdm                      4.67.1                 
typing-extensions         4.12.2                   
tzdata                    2025.2                  
ultralytics               8.3.146                 
ultralytics-thop          2.0.14                   
urllib3                   2.2.3                   
vc                        14.42               
vs2015_runtime            14.42.34433          
wheel                     0.44.0           
zipp                      3.20.2                   